#!/bin/bash

if [ -z "$1" ]; then 
  echo ""
  exit 1
fi

if [ $1 = "create" ] || [ $1 = "cr" ]; then
if [ -d "gbdir/" ]; then 
  echo "[GarbageMan] - You already have a collection directory" 
else
  mkdir gbdir
  echo "[GarbageMan] - Created garbage collection directory." 
  fi
fi

if [ $1 = "get" ] || [ $1 = "gt" ]; then
  echo "[GarbageMan] - Looking for $2"
if [ -d "gbdir/" ]; then 
  echo "[GarbageMan]  - collecting your garbage."
 mv $2 gbdir/
else
  echo "[GarbageMan]  - collecting your garbage."
  mkdir gbdir
  mv $2 gbdir/
fi
fi


if [ $1 = "clean" ] || [ $1 = "cl" ]; then
if [ -d "gbdir/" ]; then 
trashcount=`find gbdir -type f | wc -l`
  echo "[GarbageMan] - I found $trashcount trash's files"
 mv gbdir/ /tmp/gbcollected
  echo "[GarbageMan]  - collecting your garbage." 
else
 echo "[GarbageMan]  - You don't have a garbage collection directory" 
fi

fi
if [ $1 = "cleanforce" ] || [ $1 = "clf" ] || [ $1 = "cleanf" ]; then
if [ -d "gbdir/" ]; then 
trashcount=`find gbdir -type f | wc -l`
  echo "[GarbageMan] - I found $trashcount trash's files"
 rm -rf gbdir/ 
  echo "[GarbageMan]  - Cleaning your garbage directory." 
else
 echo "[GarbageMan]  - You don't have a garbage collection directory" 
fi

fi
