#!/bin/bash

if [ -z "$1" ]; then 
  echo ""
  exit 1
fi

if [ $1 = "create" ] || [ $1 = "cr" ]; then
if [ -d "$HOME/.gbdir" ]; then 
  echo "[GarbageMan] - you already have a store garbage directory" 
else
  mkdir $HOME/.gbdir
  echo "[GarbageMan] - your directory to store garbage has been created successfully." 
  fi
fi

if [ $1 = "get" ] || [ $1 = "gt" ]; then
  echo "[GarbageMan] - Looking for $2"
if [ -d "$HOME/.gbdir" ]; then 
  echo "[GarbageMan]  - trash collected"
 mv $2 $HOME/.gbdir
else
  echo "[GarbageMan]  - trash collected"
  mkdir $HOME/.gbdir
  mv $2 $HOME/.gbdir
fi
fi


if [ $1 = "clean" ] || [ $1 = "cl" ]; then
if [ -d "$HOME/.gbdir" ]; then 
trashcount=`find $HOME/.gbdir -type f | wc -l`
  echo "[GarbageMan] - I found $trashcount trash's files"

 mv $HOME/.gbdir/ /tmp/gbcollected$RANDOM
  echo "[GarbageMan]  - your trash was collected by the garbage man" 
else
 echo "[GarbageMan]  - you don't have a store garbage directory" 
fi

fi
if [ $1 = "cleanforce" ] || [ $1 = "clf" ] || [ $1 = "cleanf" ]; then
if [ -d "$HOME/.gbdir" ]; then 
trashcount=`find gbdir -type f | wc -l`
  echo "[GarbageMan] - i found $trashcount trash's files"
 rm -rf $HOME/.gbdir 
  echo "[GarbageMan]  - incinerate your trash" 
else
 echo "[GarbageMan]  - you don't have a store garbage directory" 
fi

fi
